### List all messages
GET http://localhost:3000/messages


### signup the user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "manish@gmail.com",
  "password": "13@322!thjghgfdnb"
}


### Get a All user based on Email
GET http://localhost:3000/auth?email=Mohan@gmail.com

### Get a particular user with their ID
GET http://localhost:3000/auth/3



### Remove a particular user with their ID
DELETE http://localhost:3000/auth/9


### Update a user
PATCH http://localhost:3000/auth/15
content-type: application/json

{
  "password": "aaaaa"
}